### PR TITLE
make graph more meaningful

### PR DESCRIPTION
**Pull request by overcuriousity**
if a search with multiple usernames is launched, it creates an additional site node where they both are found.  advantages:
- better recognition, that users have a connection with each other
- better detection of false positives when launching a search with two fake usernames (site node = definite false positive)

### CODE REVIEW

**Comment by soxoj** [comment]
Thanks again! <3 
That's a pretty big change of logic. Could you show some examples before/after?

**Comment by overcuriousity** [comment]
Sure!


Before:
image

After:
image

Unfortunately, I noticed that i might have broken some other logic (displaying nodes extracted by parsing?). 

But the idea is, that username nodes actually have a connection across some hops if they both have an account on the same platform.

Please feel free to close PR as its currently breaking more than doing any good...

**Comment by soxoj** [comment]
This is quite good!

I will not close the PR, ofc - these are good changes, and they will be merged!
But I want to make sure that no other logic breaks and fix it if necessary.

I’ll test everything and think about tests for the future; this will take some time 👍

**Comment by overcuriousity** [comment]
Great news, appreciate it!

**Comment by overcuriousity** [comment]
Fixed. Problem was caused by the same issue as the one resolved in #1975.

**Comment by overcuriousity** [comment]
image

**Pull request merged**
