### PR TITLE
Created web frontend launched via --web flag

### PR DESCRIPTION
**Pull request by overcuriousity**
I created a simple lightweight flask frontend.
This is a draft and will receive the additional commandline flags as options.

Frontend can be launched by specifying --web to the launching command, with optional port.

Creates all of the export options and offers them as download, created the graph and embeds it to the results page.

If not merged, I will possibly maintain a fork. I think its lightweight enough to be merged.

Feedback approved.

### CODE REVIEW

**Comment by soxoj** [comment]
Wow, that's amazing! Of course, I will merge it! 
I couldn't get around to this for many years, but you've finally done it.
Thank you so much! ❤️ 🚀

I'll squash and merge it later. The only thing I see that needs fixing is adding a new argument to the tests in test_cli, so all checks pass successfully. I can create a PR with this fix for your fork later, but you can probably address it more quickly.

**Comment by overcuriousity** [comment]
Very happy to see my PR seems useful to you!

I can see from the sourcecode how much effort is going into this and would be happy to participate. 

Doing so, I will do some further PRs on the webinterface, but unfortunately am not familiar with the pytest and poetry sections.

**Comment by soxoj** [comment]
Ok, I fixed tests, please, merge this PR into your repo: https://github.com/overcuriousity/maigret/pull/3

**Comment by overcuriousity** [comment]
merged your PR, but had to add a critical bugfix (webinterface launching always without arg).
test_cli.py was adjusted with "None" default argument for the --web flag and passes.

**Pull request merged**
