### PR TITLE
Improving the web interface

### PR DESCRIPTION
**Pull request by overcuriousity**
Made some improvements to the web interface and removed some options for now which are useless/don´t work properly yet.

image

### CODE REVIEW

**Comment by overcuriousity** [comment]
Still Subject to change. Will contribute Images to the main README as I consider the interface done.

**Comment by soxoj** [comment]
Amazing! 🚀 Thanks a lot again! 🔥 

Do I understand correctly that the interface is finished?

A small clarification: which search options will be enabled by default?

**Comment by overcuriousity** [comment]
Happy to help!

Visually i would consider it **pretty finished**, but i want to add the missing options to basically have all options available as they exist in the CLI and make sense to have on a web interface.

The **default search Parameters** are basically the same as in CLI without flags (top 500, 30s timeout, nothing else) plus any available exports.

I couldn´t figure out how to have the recursive extracting enabled consistently yet, however.
Would like that to be enabled by default as I think a maximalist approach would be better for the web interface - maybe you could give me a hand there.

**Comment by soxoj** [comment]
> Would like that to be enabled by default
Agree! 

Is it enough to enable the `parsing_enabled` flag, or is there something else needed?
I can take a look myself a bit later.

**Comment by soxoj** [comment]
I tested it, wonderful!

Ok, in what order should the PRs be merged?

**Comment by overcuriousity** [comment]
Great!
No interference, you can merge #1975 then #1977 I suggest.

**Pull request merged**
